package nda.analysis.text;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Date;
import java.util.List;

import nda.analysis.DatasetGenerationException;
import nda.analysis.DatasetGenerator;
import nda.analysis.InvalidSetupFileException;
import nda.analysis.PatternHandler;
import nda.analysis.Setup;


/**
 * 
 * @author Giuliano Vilela
 */
public class TextDatasetGenerator extends DatasetGenerator {
    /**
     * @param setupFilepath
     * @throws FileNotFoundException
     * @throws InvalidSetupFileException
     */
    public TextDatasetGenerator(String setupFilepath)
    throws FileNotFoundException, InvalidSetupFileException {
        super(setupFilepath);
    }


    /**
     * @param _setup
     */
    public TextDatasetGenerator(Setup setup) {
        super(setup);
    }


    /**
     * Create Weka ARFF files in the output directory.
     * 
     * @see nda.analysis.DatasetGenerator#generate()
     */
    @Override
    public void generate() throws DatasetGenerationException {
        System.out.println("Generating datasets...");

        File outputDir = new File(setup.getOutputDirectory());
        if (!outputDir.mkdir()) {
            throw new DatasetGenerationException("Cant create dir: " + outputDir);
        }

        for (Setup.Dataset dataset : setup.getDatasets()) {
            System.out.println("Building dataset " + dataset.getName() + " ...");

            System.out.println(" - extracting patterns...");
            List<PatternHandler> list = buildDatasetAll(dataset);

            for (PatternHandler patternHandler : list) {
                String weka_str = patternHandler.toWekaFormat();
                String file_str = formatWekaStr(weka_str);
                String filename = patternHandler.getRelation().relationName() + ".arff";

                try {
                    File file = new File(outputDir, filename);
                    System.out.println(" - writing " + file.getPath() + " ...");

                    FileWriter out = new FileWriter(file);
                    out.write(file_str);
                    out.close();
                } catch (IOException e) {
                    throw new DatasetGenerationException(e);
                }
            }
        }

        System.out.println("Done. Exiting!");
    }


    @SuppressWarnings("deprecation")
    public String formatWekaStr(String weka_str) {
        String header =
            "% -- File automatically generated by neurobjects.analysis at "
            + new Date().toGMTString() + " -- %\n"
            + "% -- Original setup file:\n%\n% ";

        String setup_str = setup.toString().replace("\n", "\n% ");
        return header + setup_str + "\n\n" + weka_str + "\n";
    }
}
