package nda.analysis;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Date;
import java.util.List;



/**
 * 
 * @author Giuliano Vilela
 */
public class SimpleDatasetGenerator extends AbstractDatasetGenerator {
    private boolean verbose;

    /**
     * @param setupFilepath
     * @throws FileNotFoundException
     * @throws InvalidSetupFileException
     */
    public SimpleDatasetGenerator(String setupFilepath)
    throws FileNotFoundException, InvalidSetupFileException {
        super(setupFilepath);
        setVerbose(false);
    }


    /**
     * @param _setup
     */
    public SimpleDatasetGenerator(Setup setup) {
        super(setup);
        setVerbose(false);
    }


    /**
     * Print information about generation progress to stdout
     */
    public void setVerbose(boolean _verbose) {
        verbose = _verbose;
    }


    /**
     * Create Weka ARFF files in the output directory.
     * 
     * @see nda.analysis.AbstractDatasetGenerator#generate()
     */
    @Override
    public void generate() throws DatasetGenerationException {
        showMessage("Generating datasets...\n");

        File outputDir = new File(setup.getOutputDirectory());
        if (!outputDir.exists() && !outputDir.mkdir()) {
            throw new DatasetGenerationException("Cant create dir: " + outputDir);
        }

        for (Setup.Dataset dataset : setup.getDatasets()) {
            showMessage("Building dataset " + dataset.getName() + " ...");

            showMessage(" - extracting patterns...");
            List<PatternHandler> list = buildDatasetAll(dataset);

            for (PatternHandler patternHandler : list) {
                String weka_str = patternHandler.toWekaFormat();
                String file_str = formatWekaStr(weka_str);
                String filename = patternHandler.getRelation().relationName() + ".arff";

                try {
                    File file = new File(outputDir, filename);
                    showMessage(" - writing " + file.getPath() + " ...");

                    FileWriter out = new FileWriter(file);
                    out.write(file_str);
                    out.close();
                } catch (IOException e) {
                    throw new DatasetGenerationException(e);
                }
            }

            showMessage("");
        }

        showMessage("Done. Exiting!");
    }


    @SuppressWarnings("deprecation")
    protected String formatWekaStr(String weka_str) {
        String header =
            "% -- File automatically generated by neurobjects.analysis at "
            + new Date().toGMTString() + " -- %\n"
            + "% -- Original setup file:\n%\n% ";

        String setup_str = setup.toString().replace("\n", "\n% ");
        return header + setup_str + "\n\n" + weka_str + "\n";
    }


    private void showMessage(String msg) {
        if (verbose)
            System.out.println(msg);
    }
}
